services:
  # main scraper
  scraper:
    build: .
    env_file:
      - .env
    container_name: reddit-scraper

    command: python app/scraper.py

    volumes:
      - ./data:/app/data

    restart: unless-stopped

  # web dashboard view at port 5000
  web:
    build: .
    container_name: reddit-dashboard

    command: python app/web/app.py

    volumes:
      - ./data:/app/data

    ports:
      - "5000:5000"

    restart: unless-stopped

  # web sql query builder/viewer at port 8001
  datasette:
    # this is a pre-built image so datasette doesn't need to be in requirements.txt
    image: datasetteproject/datasette
    platform: linux/arm64

    container_name: reddit-datasette

    command: datasette /app/data/deals.db -h 0.0.0.0 -p 8001

    volumes:
      - ./data:/app/data

    ports:
      - "8001:8001"

    restart: unless-stopped